services:
  app-dev:
    image: weatherify-app-dev
    build:
      context: ./
      dockerfile: dev.Dockerfile
    container_name: Weatherify-App-Dev
    env_file:
      - .env.local
      - .env.development
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
      - ./.next:/app/.next
    restart: unless-stopped
    ports:
      - 3000:3000
    